= Clj-Light-Refactor
Plugin that provides Clojure refactoring support in Light Table
v0.1.1, 2015-02-15: Draft release
:library: Asciidoctor
:numbered:
:idprefix:
:toc: macro

toc::[]

== Introduction



== Usage

=== Preconditions (Important !)
* The LightTable Clojure plugin (bundles with Light Table so a no-op)
* The LightTable Paredit plugin (__TODO: Hoping to get rid of this as a dependency__)
* You need the refactor-nrepl middleware setup (see below)


==== refactor-nrepl
Add the following, either in your project's __project.clj__, or in the :user profile found at __~/.lein/profiles.clj__:
[source,clojure]
----
;; if you just want to try out Dependency autocompletion and find usages
:plugins [[refactor-nrepl "0.2.2"]]

;; If you'd like to try out the bleeding edge stuff (i.e the rest)
:plugins [[refactor-nrepl "0.3.0-SNAPSHOT"]
          [cider/cider-nrepl "0.8.2"]]
----

==== Limitations
* Profiles are not handled particularily well (ie might throw exceptions, or some operation results in a noop when they shouldn't)
* clean-ns doesn't handle/analyze require import and refer (:refer, :import :refer does). This is a
downstream https://github.com/clojure-emacs/refactor-nrepl/issues/32[issue] with refactor-nrepl


=== Introduce ns
Command: **Clojure refactor: Introduce ns**

Adds toplevel namespace definition. Deduces ns from filename of editor and source-paths in project.clj.
Finds project.clj either by explicit connection or searching up for a project.clj file.

WARNING: If you have overridden source-paths in a profile definition in your project.clj. This feature will not
pick up that (currently)


=== Dependency autocompletion
Autocomplete functionality for filling in dependency vectors in your _project.clj_ files.

.Usage: (To be improved!)
* Open project.clj file
* Ensure it's tied to a project connection (Do an eval (cmd/ctrl +l) or invoke the command **Clojure refactor: Ensure editor connected**)
* When you start typing (might lag a little the first time), the autocompleter will suggest from all available clojars artifacts
* When you select an item from the autocompleter one of two things happens:
** If the selected artifact has only one version, the version indentifier is filled in
** If the artifact has multiple versions, a select with version (sorted) is shown for selection

NOTE: This feature has quite a few rough edges, so consider it a incubating idea more than anything else


=== Hotload dependency
Feature to allow hotloading of a new dependeny in your current repl session.

.Usage
* Open project.clj file
* Add a dependency in the __:dependency__ vector
* With the cursor inside the vector for your dep select the command **Refactor: Hotload dependency**
* Any errors are displayed inline

NOTE: The feature only clojars artifacts. Be aware there is no unload feature !

=== Find usages
Finds occurrences of symbols like defs and defns both where they are defined (if available) and where they are used.

.Usage:
* Move your cursor to an applicable symbol
* Invoke the command: **Clojure refactor: Find usages**
* If the editor isn't connected to a project, it will try to do so using Light Table std connect feature.
* Search results are shown in a separate tab for "Find usages" (You can move this tab to a separate tabset, it will be reused for all find usages searches)

NOTE: If there wasn't a connection for your project in the light table connect bar, you probably will have to reinvoke the command


=== Cleanup ns
Will clean up your namespace definition (removing unused, sort etc). See https://github.com/clojure-emacs/refactor-nrepl#clean-ns[here] for details

.Usage:
* When in an editor invoke the command **Clojure refactor: Cleanup ns**
* If any cleanup was necessary, your namespace declaration was updated

NOTE: The command works on the file, so you need to make sure you saved any changes to the namespace declaration
before you invoke it. If replacement was performed, the changes are not automatically saved.

=== Resolve missing
Tries to resolve the symbol at point and require or import the missing var.

.Usage:
* When in an editor place the cursor at a symbol and invoke the command **Clojure refactor: Resolve missing**
* If only one result, it is added to the ns declaration, if more than one suggestion is available you
are prompted to select one
* When added the ns form is also reformatted


TIP: Also works for records and types. You can undo the effect of this command using cmd/ctrl+z. This command
doesn't attempt to clean-up or be intelligent about duplicates etc. Thats handled by **Cleanup ns**

.Example - require:
[source,clojure]
----
;; With focus on this token, If you invoke the command with clojure.java.jdbc in your classpath
sql/query

;; The following is added to your namespace :require form
[clojure.java.jdbc :as sql]
----

.Example - import:
[source,clojure]
----
;; With focus on this token, If you invoke the command with clojure.java.jdbc in your classpath
LinkedList

;; The following is added to your namespace :import form
(java.util.LinkedList)
----






== Credits
* https://github.com/clojure-emacs/refactor-nrepl[refactor-nrepl] - nREPL middleware to support refactorings in an editor agnostic way.

== Contributing
Pull requests are most welcome. Please do not include the transpiled files (*_compiled*) in the PR.

== History
* Pending first version

== License
MIT, same as Light Table. See LICENSE.md for details.
